{
 "title": "AAP-INSIGHTS",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number of job ran",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name as job_name, COUNT(name)\r\nFROM job \r\nWHERE finished >= '${__from:date:YYYY-MM-DD} 01:00' AND finished <= '${__to:date:YYYY-MM-DD} 01:00'\r\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Job ran by job name",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name AS Job_Name, COUNT(name) FROM job GROUP BY name LIMIT 50 "
    }
   ]
  },
  {
   "title": "Job average duration in seconds",
   "type": "barchart",
   "description": "Job average duration in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT name as job_name, AVG(elapsed) as duration\r\nFROM job\r\nWHERE finished >= '${__from:date:YYYY-MM-DD} 01:00' AND finished <= '${__to:date:YYYY-MM-DD} 01:00'\r\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Job average duration in seconds",
   "type": "table",
   "description": "Job average duration in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT name as job_name, AVG(elapsed) as duration\r\nFROM job\r\nWHERE finished >= '${__from:date:YYYY-MM-DD} 01:00' AND finished <= '${__to:date:YYYY-MM-DD} 01:00'\r\nGROUP BY name"
    }
   ]
  },
  {
   "title": "Job Results",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(status) \r\nfrom job\r\nWHERE finished >= '${__from:date:YYYY-MM-DD} 01:00' AND finished <= '${__to:date:YYYY-MM-DD} 01:00'\r\nGROUP BY status\r\n"
    }
   ]
  },
  {
   "title": "Total time spent on job in seconds",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT name as job_name, sum(elapsed)\r\nFROM job \r\nWHERE finished >= '${__from:date:YYYY-MM-DD} 01:00' AND finished <= '${__to:date:YYYY-MM-DD} 01:00'\r\nGROUP BY name\r\nORDER by sum(elapsed) DESC\r\n"
    }
   ]
  }
 ]
}