{
 "title": "Time Savings",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Saved time by jobs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time.job, (((COUNT(job.name)*time.time)) - SUM(job.elapsed) )/ 60 AS saved_time \r\nFROM time JOIN job ON time.job=job.name\r\nWHERE job.finished >= '${__from:date:YYYY-MM-DD} 01:00' AND job.finished <= '${__to:date:YYYY-MM-DD} 01:00'\r\nGROUP BY time.job, time.time"
    }
   ]
  },
  {
   "title": "Percentual of saved time by job",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time.job, (((COUNT(job.name)*time.time)) - SUM(job.elapsed)) / (COUNT(job.name)*time.time)\r\nFROM time JOIN job ON time.job=job.name\r\nWHERE job.finished >= '${__from:date:YYYY-MM-DD} 01:00' AND job.finished <= '${__to:date:YYYY-MM-DD} 01:00'\r\nGROUP BY time.job, time.time\r\nHAVING (((COUNT(job.name)*time.time)) - SUM(job.elapsed)) > 0"
    }
   ]
  },
  {
   "title": "Time spent by manual jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT job, time as manual_time\r\nfrom time\r\n"
    }
   ]
  }
 ]
}