package org.app.model;

public enum JobFields {
    ID, POLYMORPHIC_CTYPE_ID, MODEL, ORGANIZATION_ID, ORGANIZATION_NAME, EXECUTION_ENVIRONMENT_IMAGE, INVENTORY_ID, INVENTORY_NAME, CREATED, NAME, UNIFIED_JOB_TEMPLATE_ID, LAUNCH_TYPE, SCHEDULE_ID, EXECUTION_NODE, CONTROLLER_NODE, CANCEL_FLAG, STATUS, FAILED, STARTED, FINISHED, ELAPSED, JOB_EXPLANATION, INSTANCE_GROUP_ID, INSTALLED_COLLECTIONS, ANSIBLE_VERSION, FORKS

}
